name: OpenJDK Build

on:
  workflow_dispatch:

env:
  branch: lw5

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout OpenJDK
      uses: actions/checkout@v3
      with:
        repository: openjdk/valhalla
        ref: ${{ env.branch }}
    - name: Get Commit Id
      id: commitid
      run: |
        echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Install Bootstrap JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '20'
    - name: Install Requirements
      run: |
        sudo apt-get install libasound2-dev libcups2-dev libx11-dev libxext-dev libxrender-dev libxrandr-dev libxtst-dev libxt-dev
    - name: Build
      run: |
        bash configure --with-native-debug-symbols=none --with-version-opt=valhalla-${{ env.branch }}-${{ steps.commitid.outputs.sha }} --with-version-build=$${{ github.run_number }} --with-vendor-name=javaalmanac.io
        make images
    - name: Smoke Test
      run: |
        build/linux-x86_64-server-release/images/jdk/bin/java --version
    - name: Create Package
      run: |
        tar -czvf jdk-valhalla.tar.gz -C build/linux-x86_64-server-release/images jdk
        sha256sum jdk-valhalla.tar.gz
    - name: Upload Artifact
      uses: pyTooling/Actions/releaser@v0.4.6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest-build
        files: jdk-valhalla.tar.gz
