name: OpenJDK Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout OpenJDK
      uses: actions/checkout@v3
      with:
        repository: openjdk/valhalla
        ref: lw5
    - name: Install Bootstrap JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '20'
    - name: Install requirements
      run: |
        sudo apt-get install libasound2-dev libcups2-dev libx11-dev libxext-dev libxrender-dev libxrandr-dev libxtst-dev libxt-dev
    - name: Build
      run: |
        bash configure --with-native-debug-symbols=none
        make images
    - name: Create Package
      run: |
        tar -czvf jdk-valhalla.tar.gz -C build/linux-x86_64-server-release/images jdk
        sha256sum jdk-valhalla.tar.gz
    - name: Upload Artifact
      uses: pyTooling/Actions/releaser@v0.4.6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest-build
        files: jdk-valhalla.tar.gz
