name: OpenJDK Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout OpenJDK
      uses: actions/checkout@v3
      with:
        repository: openjdk/valhalla
        ref: lw5
    - name: Install bootstrap JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '20'
    - name: Build
      run: |
        bash configure
        make images
